version: '3.9'

services:
  postgres:
    image: 'postgres:16'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 01
      POSTGRES_DB: ms-store
    ports:
      - "5432:5432"

  api:
    build:
      context: ..
      dockerfile: ms-store/Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ms-store
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 01
    ports:
      - "8082:8082"